name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v2
      - uses: jurassiscripts/setup-velociraptor@v2
      - name: Run update
        env:
          VR_HOOKS: "false"
        run: vr update
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "add: new 4-panel"
