name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

runs:
  using: composite
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Deno Run
      run: deno run -q -A main.ts

    - name: Deno Format
      run: deno fmt docs

    - name: Commit the changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'add: new 4-panel'
